# Generated by Django 2.1.8 on 2019-05-13 00:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.employee_image_file_path),
        ),
    ]
